CREATE DATABASE IF NOT EXISTS school_directory;
USE school_directory;

CREATE TABLE IF NOT EXISTS schools (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  contact VARCHAR(50) NOT NULL,
  email_id VARCHAR(120) NOT NULL,
  image VARCHAR(255) NOT NULL,

  board VARCHAR(50) NULL,
  hostel VARCHAR(10) NULL,
  type VARCHAR(20) NULL,
  medium VARCHAR(50) NULL,

  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
